### ISSUE TITLE
Missing some info

### ISSUE THREAD

**Issue by renatomserra** [tmshkr/blue-green-beanstalk#5]
Heya, thanks for creating this.
The documentation seems to be missing some info like required env vars/secrets with aws keys, or am i mistaken?

**Comment by tmshkr** [comment]
Hi @renatomserra, thanks for checking it out! There's an [example repo](https://github.com/tmshkr/blue-green-beanstalk-example) that you can use as a template to get started. It includes a CloudFormation template, which will create the necessary IAM resources to deploy via the GitHub OIDC provider.

Feel free to open an issue on that repo if anything is unclear or isn't working correctly.
